#simple_model is the name space
sailboat:
    # based on https://wiki.ros.org/ros_control this controller reads the state 
    # of all the joints
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    sail_joint_position_controller:
        #this controller recieves position and via PID it takes care of the effort
        # needed to move the joint. based on https://wiki.ros.org/ros_control
        # type: position_controllers/JointPositionController
        #type: velocity_controllers/JointVelocityController
        type: position_controllers/JointPositionController
        joint: sail_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    rudder_joint_position_controller:
        #this controller recieves position and via PID it takes care of the effort
        # needed to move the joint. based on https://wiki.ros.org/ros_control
        # type: position_controllers/JointPositionController
        #type: velocity_controllers/JointVelocityController
        type: position_controllers/JointPositionController
        joint: rudder_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}